name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install Node.js (optional but recommended to specify version)
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm
      
      # Install dependencies and build with pnpm
      - name: Install dependencies and build
        run: pnpm install && pnpm run build
      
      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ABHYASI_4BA9C }}
          channelId: live
          projectId: abhyasi-4ba9c
